Repository vivid-planet/comet, pull requests merged in 2021-04, with the labels that each got.

#335 Error boundaries
  package-lock.json
  packages/admin-stories/package.json
  packages/admin-stories/src/admin/error-handling/ErrorBoundary.tsx
  packages/admin-stories/src/admin/error-handling/RouteWithErrorBoundary.tsx
  packages/admin/package.json
  packages/admin/src/error/errorboundary/ErrorBoundary.sc.ts
  packages/admin/src/error/errorboundary/ErrorBoundary.tsx
  packages/admin/src/error/errorboundary/RouteWithErrorBoundary.tsx
  packages/admin/src/error/errorboundary/index.ts
  packages/admin/src/error/index.ts
  packages/admin/src/index.ts
Labels: dependencies, enhancement

#307 Add styling-ability with theme-overrides
  packages/admin-rte/CHANGELOG.md
  packages/admin-rte/src/core/Controls/BlockTypesControls.sc.ts
  packages/admin-rte/src/core/Controls/BlockTypesControls.tsx
  packages/admin-rte/src/core/Controls/ControlButton.sc.ts
  packages/admin-rte/src/core/Controls/ControlButton.tsx
  packages/admin-rte/src/core/Controls/FeaturesButtonGroup.sc.ts
  packages/admin-rte/src/core/Controls/FeaturesButtonGroup.tsx
  packages/admin-rte/src/core/Controls/LinkControls.sc.ts
  packages/admin-rte/src/core/Controls/LinkControls.tsx
  packages/admin-rte/src/core/Controls/Toolbar.sc.ts
  packages/admin-rte/src/core/Controls/Toolbar.tsx
  packages/admin-rte/src/core/Controls/useBlockTypes.tsx
  packages/admin-rte/src/core/Rte.sc.ts
  packages/admin-rte/src/core/Rte.tsx
  packages/admin-rte/src/core/types.ts
  packages/admin-rte/src/field/createFinalFormRte.tsx
  packages/admin-rte/src/themeAugmentation.ts
Labels: enhancement

#347 Upgrade storybook to 6.2.4
  package-lock.json
  packages/admin-stories/.storybook/addons.ts
  packages/admin-stories/.storybook/assets/comet-logo-header.svg
  packages/admin-stories/.storybook/main.js
  packages/admin-stories/.storybook/main.ts
  packages/admin-stories/.storybook/manager.ts
  packages/admin-stories/.storybook/preview-head.html
  packages/admin-stories/.storybook/preview.tsx
  packages/admin-stories/.storybook/theme.tsx
  packages/admin-stories/.storybook/webpack.config.ts
  packages/admin-stories/package.json
  packages/admin-stories/src/docs/Intro.stories.mdx
Labels: dependencies

#348 Use stored state hook
  CHANGELOG.md
  packages/admin-stories/.storybook/preview.tsx
  packages/admin-stories/src/admin/hooks/stored-state/IncrementStoredState.tsx
  packages/admin-stories/src/docs/comet/admin/hooks.stories.mdx
  packages/admin/src/hooks/index.ts
  packages/admin/src/hooks/useStoredState.ts
  packages/admin/src/index.ts
Labels: enhancement

#349 Story: useStoredState() - add sessions storage story
  packages/admin-stories/src/admin/hooks/stored-state/IncrementStoredState.tsx
  packages/admin-stories/src/admin/hooks/stored-state/SessionStorage.tsx
  packages/admin-stories/src/docs/comet/admin/hooks.stories.mdx
Labels: story-only

#352 Add comet color icon
  packages/admin-icons/src/CometColor.tsx
  packages/admin-icons/src/index.ts
Labels: enhancement

#354 Fix peerDependencies referencing own packages for 2.0
  packages/admin-color-picker/package.json
  packages/admin-date-picker/package.json
  packages/admin-react-select/package.json
Labels: bug

#355 update package.lock
  package-lock.json
Labels: bug

#351 Add roboto font to storybook
  package-lock.json
  packages/admin-stories/.storybook/preview.tsx
  packages/admin-stories/package.json
Labels: story-only

#356 remove graphql-tag
  package-lock.json
  package.json
  packages/admin-stories/src/admin/stack/StackTableFormQueryAtStack.tsx
  packages/admin-stories/src/admin/stack/StackTableFormQueryInTable.tsx
  packages/admin-stories/src/admin/table/TableBesidesForm.tsx
  packages/admin-stories/src/admin/table/TableBesidesFormSelectionHooks.tsx
  packages/admin-stories/src/admin/table/TableExportAllPages.tsx
  packages/admin-stories/src/admin/table/TableExportWithLimit.tsx
  packages/admin-stories/src/admin/table/TableExportWithLimitFilter.tsx
  packages/admin-stories/src/admin/table/TableFilter.tsx
  packages/admin-stories/src/admin/table/TableFilterPagingSort.tsx
  packages/admin-stories/src/admin/table/TablePaging.tsx
  packages/admin-stories/src/admin/table/TableResetFilter.tsx
  packages/admin-stories/src/admin/table/TableSort.tsx
  packages/admin/src/buildRestMutation.tsx
Labels: dependencies, incompatible

#361 Explicitly only import types from theme-augmentation
  packages/admin-theme/src/getThemeOptions.ts
Labels: bug

#358 Configure rte-colors using props instead of custom rte-key in theme
  CHANGELOG.md
  codemods/2.0.0/update-theme.ts
  packages/admin-rte/src/core/Controls/BlockTypesControls.tsx
  packages/admin-rte/src/core/Controls/ControlButton.tsx
  packages/admin-rte/src/core/Controls/FeaturesButtonGroup.tsx
  packages/admin-rte/src/core/Controls/LinkControls.tsx
  packages/admin-rte/src/core/Controls/Toolbar.tsx
  packages/admin-rte/src/core/Rte.tsx
  packages/admin-rte/src/core/types.ts
  packages/admin-rte/src/core/utils/getRteTheme.ts
  packages/admin-rte/src/themeAugmentation.ts
  packages/admin-stories/.storybook/preview.tsx
  packages/admin/src/mui/ThemeProvider.tsx
Labels: incompatible
