Repository vivid-planet/comet, pull requests merged in 2021-03, with the labels that each got.

#326 Fix too restrictive peer dependencies
  CHANGELOG.md
  lint-staged.config.js
  package-lock.json
  packages/admin-stories/package.json
  packages/admin/package.json
Labels: dependencies, enhancement

#324 Add story showing how static values can be displayed in a form
  packages/admin-stories/src/admin/form/Typography.tsx
Labels: story-only

#320 Pass innerRef to sc.TableBodyRow
  CHANGELOG.md
  packages/admin/src/table/Table.tsx
Labels: enhancement

#309 Handle Submit Error in EditDialog
  CHANGELOG.md
  packages/admin/src/DirtyHandler.tsx
  packages/admin/src/DirtyHandlerApiContext.tsx
  packages/admin/src/EditDialog.tsx
  packages/admin/src/FinalForm.tsx
  packages/admin/src/form/SubmitResult.tsx
Labels: bug

#310 Rename react-select with "Comet" and add common theming support
  packages/admin-react-select/CHANGELOG.md
  packages/admin-react-select/src/ReactSelect.styles.ts
  packages/admin-react-select/src/ReactSelect.tsx
  packages/admin-react-select/src/themeAugmentation.ts
Labels: incompatible

#328 fix(admin-color-picker): react-color dependency is updateable and fix…
  package-lock.json
  packages/admin-color-picker/package.json
  packages/admin-color-picker/src/core/HexInput.tsx
Labels: bug, dependencies

#332 refactor: cleanup dependencies
  package-lock.json
  package.json
  packages/admin-color-picker/package.json
  packages/admin-color-picker/src/core/HexInput.tsx
  packages/admin-date-picker/package.json
  packages/admin-react-select/package.json
  packages/admin-react-select/src/FinalFormReactSelect.tsx
  packages/admin-react-select/src/ReactSelect.tsx
  packages/admin-rte/package.json
  packages/admin-stories/package.json
  packages/admin/package.json
  packages/admin/src/FinalForm.tsx
Labels: dependencies

#305 Improve styling and customizing of color picker
  packages/admin-color-picker/CHANGELOG.md
  packages/admin-color-picker/src/core/ColorPicker.styles.ts
  packages/admin-color-picker/src/core/ColorPicker.tsx
  packages/admin-color-picker/src/core/HexInput.tsx
  packages/admin-color-picker/src/core/Palette.tsx
  packages/admin-color-picker/src/core/PickedColor.tsx
  packages/admin-color-picker/src/core/Picker.tsx
  packages/admin-color-picker/src/themeAugmentation.ts
  packages/admin-stories/src/admin-color-picker/ColorPicker.tsx
Labels: incompatible
