Repository vivid-planet/comet, pull requests merged in 2021-06, with the labels that each got.

#410 Fix z-index of split-button menu
  packages/admin/src/common/buttons/split/SplitButton.tsx
Labels: bug

#405 Styling fixes and adjustments in InputBase
  packages/admin-theme/src/MuiOverrides/MuiSelect.ts
  packages/admin/src/form/InputBase.tsx
Labels: bug, enhancement

#404 Add createCometTheme function
  package-lock.json
  packages/admin-stories/.storybook/preview.tsx
  packages/admin-theme/package.json
  packages/admin-theme/src/AdminOverrides/formFieldContainer.ts
  packages/admin-theme/src/AdminOverrides/getAdminOverrides.ts
  packages/admin-theme/src/AdminOverrides/inputBase.ts
  packages/admin-theme/src/AdminOverrides/menuCollapsibleItem.ts
  packages/admin-theme/src/AdminOverrides/menuItem.ts
  packages/admin-theme/src/AdminOverrides/stackBreadcrumbs.ts
  packages/admin-theme/src/AdminOverrides/toolbaritem.ts
  packages/admin-theme/src/MuiOverrides/MuiButton.ts
  packages/admin-theme/src/MuiOverrides/MuiButtonGroup.ts
  packages/admin-theme/src/MuiOverrides/MuiCheckbox.ts
  packages/admin-theme/src/MuiOverrides/MuiDialogActions.ts
  packages/admin-theme/src/MuiOverrides/MuiDialogContent.ts
  packages/admin-theme/src/MuiOverrides/MuiDialogContentText.ts
  packages/admin-theme/src/MuiOverrides/MuiDrawer.ts
  packages/admin-theme/src/MuiOverrides/MuiPaper.ts
  packages/admin-theme/src/MuiOverrides/MuiRadio.ts
  packages/admin-theme/src/MuiOverrides/MuiSelect.ts
  packages/admin-theme/src/MuiOverrides/MuiSvgIcon.ts
  packages/admin-theme/src/MuiOverrides/MuiSwitch.ts
  packages/admin-theme/src/MuiOverrides/getMuiOverrides.ts
  packages/admin-theme/src/createCometTheme.ts
  packages/admin-theme/src/getThemeOptions.ts
  packages/admin-theme/src/index.ts
Labels: incompatible

#402 Allow full-width for horizontal fields
  packages/admin-theme/src/AdminOverrides/formFieldContainer.ts
  packages/admin/src/form/Field.tsx
  packages/admin/src/form/FieldContainer.tsx
Labels: bug

#416 Convert snackbar docu to new
  packages/admin-stories/src/docs/comet/admin/snackbar.stories.mdx
  packages/admin-stories/src/docs/components/Snackbar/Snackbar.stories.mdx
  packages/admin-stories/src/docs/components/Snackbar/snackbar.decorator.tsx
  packages/admin-stories/src/docs/components/Snackbar/stories/UndoSnackbar.stories.tsx
  packages/admin-stories/src/docs/components/Snackbar/stories/hideSnackbar.stories.tsx
  packages/admin-stories/src/docs/components/Snackbar/stories/showSnackbar.stories.tsx
  packages/admin-stories/src/docs/components/Snackbar/stories/useSnackbarApiHook.stories.tsx
Labels: story-only

#429 Fix fullWidth prop in FieldContainer
  packages/admin/src/form/FieldContainer.tsx
Labels: bug

#421 Update dnd
  CHANGELOG.md
  package-lock.json
  packages/admin-stories/package.json
  packages/admin-stories/src/admin/table/TableDndOrder.tsx
  packages/admin-stories/src/dnd.decorator.tsx
  packages/admin/package.json
  packages/admin/src/table/TableBodyRow.tsx
  packages/admin/src/table/TableDndOrder.tsx
Labels: incompatible

#436 Only style pre and code tags in story
  packages/admin-stories/.storybook/preview-head.html
Labels: bug
