Repository vivid-planet/comet, pull requests merged in 2021-02, with the labels that each got.

#296 RouterPrompt: add missing message callback parameters for full react-router compatibility
  CHANGELOG.md
  packages/admin/src/router/Context.tsx
  packages/admin/src/router/Prompt.tsx
  packages/admin/src/router/PromptHandler.tsx
Labels: enhancement

#299 Remove min-width of link buttons (MuiButtonGroup)
  packages/admin-rte/src/core/Controls/LinkControls.sc.ts
Labels: bug

#294 Add common clear-input-button
  CHANGELOG.md
  packages/admin-color-picker/CHANGELOG.md
  packages/admin-color-picker/src/core/ColorPicker.styles.ts
  packages/admin-color-picker/src/core/ColorPicker.tsx
  packages/admin-color-picker/src/core/HexInput.tsx
  packages/admin/src/common/ClearInputButton.tsx
  packages/admin/src/common/index.ts
  packages/admin/src/index.ts
  packages/admin/src/themeAugmentation.ts
Labels: enhancement, incompatible

#297 Change default layout and customization of FieldContainer
  CHANGELOG.md
  packages/admin-stories/src/admin-color-picker/ColorPicker.tsx
  packages/admin-stories/src/admin-react-select/FinalFormReactSelect.tsx
  packages/admin-stories/src/admin-react-select/FinalFormReactSelectDialog.tsx
  packages/admin-stories/src/admin-react-select/FinalFormReactSelectDisabledOption.tsx
  packages/admin-stories/src/admin/form/FormLayouts.tsx
  packages/admin-stories/src/admin/form/Select.tsx
  packages/admin-stories/src/admin/stack/StackTableFormQueryAtStack.tsx
  packages/admin-stories/src/admin/stack/StackTableFormQueryInTable.tsx
  packages/admin-stories/src/admin/table/TableExportWithLimitFilter.tsx
  packages/admin-stories/src/admin/table/TableFilter.tsx
  packages/admin-stories/src/admin/table/TableFilterClientside.tsx
  packages/admin-stories/src/admin/table/TableFilterPagingSort.tsx
  packages/admin-stories/src/admin/table/TableResetFilter.tsx
  packages/admin/src/form/Field.tsx
  packages/admin/src/form/FieldContainer.tsx
  packages/admin/src/form/FieldContainerLabelAbove.tsx
  packages/admin/src/form/index.ts
  packages/admin/src/themeAugmentation.ts
Labels: incompatible

#293 Add for all available form field components a story
  packages/admin-stories/src/admin/form/AllFieldComponents.tsx
  packages/admin-stories/src/admin/form/Checkbox.tsx
  packages/admin-stories/src/admin/form/Input.tsx
  packages/admin-stories/src/admin/form/Radio.tsx
  packages/admin-stories/src/admin/form/Switch.tsx
Labels: story-only

#304 Add new InputBase for use in all custom input-components in Comet
  CHANGELOG.md
  packages/admin/src/common/ClearInputButton.tsx
  packages/admin/src/form/FinalFormInput.tsx
  packages/admin/src/form/Input.ts
  packages/admin/src/form/Input.tsx
  packages/admin/src/form/InputBase.tsx
  packages/admin/src/form/Select.tsx
  packages/admin/src/form/index.ts
  packages/admin/src/form/themeAugmentation.ts
  packages/admin/src/themeAugmentation.ts
Labels: incompatible

#308 Use mui-grey-palette for default colors
  packages/admin/src/mui/ThemeProvider.tsx
Labels: bug

#300 Make controls for RTE sticky
  packages/admin-rte/src/core/Controls/Toolbar.sc.ts
  packages/admin-rte/src/core/Rte.sc.ts
Labels: bug

#280 Allow styling/customizing the menu using the theme
  CHANGELOG.md
  packages/admin-stories/src/admin/mui/Menu.tsx
  packages/admin-stories/src/admin/mui/MenuCometTheme.tsx
  packages/admin-stories/src/admin/mui/MenuDynamicVariants.tsx
  packages/admin/src/mui/MasterLayout.tsx
  packages/admin/src/mui/menu/CollapsibleItem.tsx
  packages/admin/src/mui/menu/Item.sc.tsx
  packages/admin/src/mui/menu/Item.tsx
  packages/admin/src/mui/menu/ItemAnchorLink.tsx
  packages/admin/src/mui/menu/ItemRouterLink.tsx
  packages/admin/src/mui/menu/Menu.sc.tsx
  packages/admin/src/mui/menu/Menu.styles.ts
  packages/admin/src/mui/menu/Menu.tsx
  packages/admin/src/mui/menu/index.ts
  packages/admin/src/mui/menu/useWindowSize.tsx
  packages/admin/src/themeAugmentation.ts
Labels: enhancement, incompatible
