Repository vivid-planet/comet, pull requests merged in 2021-05, with the labels that each got.

#367 Add theming to more components
  CHANGELOG.md
  packages/admin-stories/src/admin/stack/Stack.tsx
  packages/admin-stories/src/admin/stack/StackReactNodeTitle.tsx
  packages/admin-stories/src/admin/table/Table.tsx
  packages/admin-theme/src/cometAdminOverrides/breadcrumbs.ts
  packages/admin-theme/src/cometAdminOverrides/menuItem.ts
  packages/admin-theme/src/cometAdminProps/breadcrumbs.tsx
  packages/admin-theme/src/getThemeOptions.ts
  packages/admin-theme/src/index.ts
  packages/admin-theme/src/paletteOptions.ts
  packages/admin-theme/src/typographyOptions.ts
  packages/admin/src/form/FormPaper.tsx
  packages/admin/src/form/FormSection.tsx
  packages/admin/src/layout/FixedLeftRightLayout.tsx
  packages/admin/src/mui/breadcrumbs/Breadcrumbs.tsx
  packages/admin/src/stack/Stack.sc.tsx
  packages/admin/src/stack/Stack.tsx
  packages/admin/src/themeAugmentation.ts
Labels: incompatible

#124 Range slider field Component with Storybook Story
  CHANGELOG.md
  packages/admin-stories/src/admin/form/RangeInput.tsx
  packages/admin/src/form/FinalFormRangeInput.tsx
  packages/admin/src/form/index.ts
  packages/admin/src/themeAugmentation.ts
Labels: enhancement

#370 Always render label next to checkbox/radio
  packages/admin-stories/src/admin/form/AllFieldComponents.tsx
  packages/admin-stories/src/admin/form/Checkbox.tsx
  packages/admin-stories/src/admin/form/Radio.tsx
Labels: story-only

#368 Delete fixed-left-right-layout
  CHANGELOG.md
  packages/admin-stories/src/admin/table/TableBesidesForm.tsx
  packages/admin-stories/src/admin/table/TableBesidesFormSelectionHooks.tsx
  packages/admin/src/index.ts
  packages/admin/src/layout/FixedLeftRightLayout.tsx
  packages/admin/src/layout/index.ts
  packages/admin/src/themeAugmentation.ts
Labels: incompatible

#337 Error dialog
  packages/admin-stories/.storybook/preview-head.html
  packages/admin-stories/src/admin/table/GlobalErrorHandling.tsx
  packages/admin-stories/src/apollo-swapi-story.decorator.tsx
  packages/admin-stories/src/docs/comet/admin/errors/errordialog.stories.mdx
  packages/admin-stories/src/error-dialog-provider.decorator.tsx
  packages/admin/src/error/errordialog/ErrorDialog.tsx
  packages/admin/src/error/errordialog/ErrorDialogContext.tsx
  packages/admin/src/error/errordialog/ErrorDialogProvider.tsx
  packages/admin/src/error/errordialog/ErrorScope.ts
  packages/admin/src/error/errordialog/createErrorDialogApolloLink.ts
  packages/admin/src/error/errordialog/index.ts
  packages/admin/src/error/errordialog/useErrorDialog.ts
  packages/admin/src/error/index.ts
  packages/admin/src/table/useTableQuery.ts
Labels: enhancement

#396 TextArea of RTE should not be transparent
  packages/admin-rte/src/core/Rte.tsx
Labels: bug

#399 Don't set class-key that doesn't exist
  packages/admin-theme/src/MuiOverrides/MuiCheckbox.ts
  packages/admin-theme/src/MuiOverrides/MuiRadio.ts
Labels: bug

#395 Move border-bottom to paper with variant "outlined"
  packages/admin-theme/src/MuiOverrides/MuiPaper.ts
Labels: enhancement

#391 Remove styled-components styling from table
  CHANGELOG.md
  packages/admin-stories/src/admin/table/TableResponsive.tsx
  packages/admin-theme/src/cometAdminOverrides/tableBodyRow.ts
  packages/admin-theme/src/getThemeOptions.ts
  packages/admin/src/index.ts
  packages/admin/src/table/Table.sc.tsx
  packages/admin/src/table/Table.tsx
  packages/admin/src/table/TableBodyRow.tsx
  packages/admin/src/table/TableDndOrder.tsx
Labels: incompatible
